### ISSUE TITLE
Decimal unicode input on windows

### ISSUE THREAD

**Issue by lldata** [keyboardio/Kaleidoscope-Unicode#6]
Entering unicode on windows requires a special registry key to be set up.

A nice alternative would be to open for inputting unicode as decimals, with the trade off that the output are input language specific.

http://www.fileformat.info/tip/microsoft/enter_unicode.htm

> Method 2: Input-language Specific

> This method depends on the specific input language you are using.
> Press and hold down the Alt key.
> Type 0 (zero) and the decimal unicode value on the numeric keypad.
> Release the Alt key.
> 

I'd be happy to test

**Comment by lldata** [comment]
Not quite the same but I got the a simpler implementation here, that works for latin1:
https://github.com/lldata/Model01-Firmware/commit/cbc4de77b645fb20f5753624deb1462ef24faba4

**Comment by algernon** [comment]
This is a bit tougher to implement, because the whole `Unicode` plugin is set up in a way that assumes hex input. We'd need to change that first, and that's not trivial.

Seeing as I haven't touched this since november, I don't think I'll be able to work on it anytime soon. Happy to accept pull requests, and offer guidance though.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#391.
